[package]
name = "eggprobe-native"
description = "Backend-neutral native diagnostics substrate for Eggprobe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
netdev = { version = "0.46", default-features = false }
netroute = "0.4"
tokio.workspace = true

[lints]
workspace = true
